name: find_min_distance
description: A Dart package to calculate the minimum distance between two locations using latitude and longitude.

version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

author: Vansh <vanshbhardwajhere@gmail.com>
maintainer: Vansh <vanshbhardwajhere@gmail.com>

homepage: https://github.com/vanshbhardwajhere/find_min_distance
repository: https://github.com/vanshbhardwajhere/find_min_distance

topics:
  - geolocation
  - distance
  - utility

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
